services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # Forwards the local Docker socket to the container.
    # This allows the container to use the host's Docker daemon.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends. 
    command: sleep infinity 